DROP TABLE IF EXISTS sale;
DROP TABLE IF EXISTS "check";
DROP TABLE IF EXISTS customer_card;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS store_product;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS category;
